### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by DimonYoing** [supercrafter333/BetterMute#1]
Add it so that it is visible to all players in the chat that the player has been stirred up.
Add another date value so that the time is specified in days and in minutes if the time is specified in minutes"
The player silenced the player Steve for 14 days. Reason: "

**Comment by MrBlasyMSK** [comment]
I like the idea, but it would be nice if you could choose in the configuration if you want it to be made public or not (broadcast type).

```yml
Broadcast-mute: true
Broadcast-message: "{player} has been muted for {reason} until {time}"
```

**Comment by supercrafter333** [comment]
> I like the idea, but it would be nice if you could choose in the configuration if you want it to be made public or not (broadcast type).
> 
> ```yaml
> Broadcast-mute: true
> Broadcast-message: "{player} has been muted for {reason} until {time}"
> ```

Already planed

**Comment by supercrafter333** [comment]
![image](https://user-images.githubusercontent.com/53967726/159344800-9ae94bcb-a6fa-4892-ae2c-aee63c3aaa2c.png)

**Comment by MrBlasyMSK** [comment]
> ![image](https://user-images.githubusercontent.com/53967726/159344800-9ae94bcb-a6fa-4892-ae2c-aee63c3aaa2c.png)

Looks nice!

**Comment by supercrafter333** [comment]
Done in v1.1.0.
