### ISSUE TITLE
Eror

### ISSUE THREAD

**Issue by NdaruAjaa** [supercrafter333/BetterMute#14]
PocketMine-MP version: 4.15.2 [Protocol 567]
Git commit: 308cdb68631f1e4190d3741231e1219e80080e90
PHP version: 8.1.15
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: BetterMute

Error: During inheritance of JsonSerializable: Uncaught ErrorException: Return type of supercrafter333\BetterMute\libs\dktapps\pmforms\MenuOption::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/container/plugins/BetterMute.phar/src/supercrafter333/BetterMute/libs/dktapps/pmforms/MenuOption.php:53
File: plugins/BetterMute.phar/src/supercrafter333/BetterMute/libs/dktapps/pmforms/MenuOption
Line: 29
Type: E_ERROR
Backtrace:

**Comment by supercrafter333** [comment]
That's because BetterMutes virions aren't updated yet. I'll fix this error in the next days.

**Comment by NdaruAjaa** [comment]
> 

Ya
