### ISSUE TITLE
how to use the timing?

### ISSUE THREAD

**Issue by Smorted** [supercrafter333/BetterMute#15]
I can't understand how to exactly use the time for mute, can you give an example command?

i do /mute steve test 10 m
(to mute for 10 minutes)
but it doesn't work

**Comment by supercrafter333** [comment]
Hello,
sorry for my very late answer.

Please use it like that: `/mute <player> [reason] [time]`
Example: `/mute Steve "Spamming, Insults" 1d12h` -> "Steve" will be muted for spamming and insults for 1 day and 12 hours

> This issue will be closed as completed. If you have any additional questions please write them in this issue and I'll answer them.

best regards
supercrafter333

**Comment by Smorted** [comment]
unfortunately i couldn't wait and proceeded to make my own mute plugin, if i knew this, it would've saved me the effort of making a new one.

thank you for the response though!
Cheers.
