### ISSUE TITLE
/muteinfo dont work

### ISSUE THREAD

**Issue by MrBlasyMSK** [supercrafter333/BetterMute#4]
https://streamable.com/4fp0jk

Server version: 4.2.4 (git hash: 05a5e5eac126064583af2e892cb9b3cc0b0a88b6)
Compatible Minecraft version: 1.18.10 (protocol version: 486)
PHP version: 8.0.16
PHP JIT: not supported
Operating system: linux
BetterMute dev9

**Comment by supercrafter333** [comment]
I've forgot to open the next form in the code. I'll fix that this evening (UTC+01:00 / CEST)

**Comment by supercrafter333** [comment]
I've forgot your issue. I'll fix it tomorrow 😅

**Comment by MrBlasyMSK** [comment]
> I've forgot your issue. I'll fix it tomorrow 😅
![descarga (9)](https://user-images.githubusercontent.com/85447029/159805985-e99ccb22-d49c-4d8a-aa88-a8ea2e295192.png)

nah np, just joking

**Comment by MrBlasyMSK** [comment]
/ban @supercrafter333 He have not corrected the plugin
